[workspace]
resolver = "2"
members = [
    "syncserver-common",
    "syncserver-db-common",
    "syncserver-settings",
    "syncserver-web-common",
    "syncstorage-db",
    "syncstorage-db-common",
    "syncstorage-mysql",
    "syncstorage-settings",
    "syncstorage-spanner",
    "syncstorage-web",
    "tokenserver-auth",
    "tokenserver-common",
    "tokenserver-db",
    "tokenserver-settings",
    "tokenserver-web",
    "syncserver",
]
default-members = ["syncserver"]

[profile.release]
# Enables line numbers in Sentry reporting
debug = 1
