version: '3'
services:
    sync-db:
        image: gcr.io/cloud-spanner-emulator/emulator
        ports:
            - "9010:9010"
            - "9020:9020"
        environment:
            PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    sync-db-setup:
        image: app:build
        depends_on:
            - sync-db
        restart: "no"
        entrypoint: "/app/scripts/prepare-spanner.sh"
        environment:
            SYNC_SYNCSTORAGE__SPANNER_EMULATOR_HOST: sync-db:9020
    syncserver:
        # NOTE: The naming in the rest of this repository has been updated to reflect the fact
        # that Syncstorage and Tokenserver are now part of one repository/server called
        # "Syncserver" (updated from "syncstorage-rs"). We keep the legacy naming below for
        # backwards compatibility with previous Docker images.
        image: ${SYNCSTORAGE_RS_IMAGE:-syncstorage-rs:latest}
        restart: always
        ports:
            - "8000:8000"
        depends_on:
            - sync-db-setup
        environment:
            SYNC_HOST: 0.0.0.0
            SYNC_MASTER_SECRET: secret0
            SYNC_SYNCSTORAGE__DATABASE_URL: spanner://projects/test-project/instances/test-instance/databases/test-database
            SYNC_SYNCSTORAGE__SPANNER_EMULATOR_HOST: sync-db:9010
        # Application runs off of port 8000.
        # you can test if it's available with
        # curl "http://localhost:8000/__heartbeat__"
