version: '3'
services:
  sync-db:
  sync-db-setup:
  syncserver:
    depends_on:
      - sync-db-setup
    # TODO: either syncserver should retry the db connection
    # itself a few times or should include a wait-for-it.sh script
    # inside its docker that would do this for us.
    entrypoint: >
      /bin/sh -c "
        sleep 15;
        /app/bin/syncserver;
      "
  spanner-e2e-tests:
    depends_on:
      - mock-fxa-server
      - syncserver
    image: app:build
    privileged: true
    user: root
    environment:
      MOCK_FXA_SERVER_URL: http://mock-fxa-server:6000
      SYNC_HOST: 0.0.0.0
      SYNC_MASTER_SECRET: secret0
      SYNC_SYNCSTORAGE__DATABASE_URL: spanner://projects/test-project/instances/test-instance/databases/test-database
      SYNC_SYNCSTORAGE__SPANNER_EMULATOR_HOST: sync-db:9010
    entrypoint: >
      /bin/sh -c "
        sleep 28; python3 /app/tools/integration_tests/run.py 'http://localhost:8000#secret0'
      "
