[package]
name = "tokenserver-common"
version = "0.13.1"
edition = "2021"

[dependencies]
backtrace = "0.3.61"
http = "0.2.6"
serde = "1.0"
syncserver-common = { path = "../syncserver-common" }
syncserver-db-common = { path = "../syncserver-db-common" }
